### ISSUE TITLE
Data.AVL.Tree.avlUpdate looks very wrong

### ISSUE THREAD

**Issue by treeowl** [jfdm/idris-containers#2]
I see no indication that it preserves the ordering invariant. What you probably actually want is a deletion function that also returns an indication of whether the deleted element was previously in the tree.

**Comment by treeowl** [comment]
BTW, I don't know Idris, but shouldn't dependent types be able to catch these sorts of mistakes, by requiring a proof of appropriate ordering in order to apply a node constructor?

**Comment by treeowl** [comment]
Or is that too expensive or something?

**Comment by jfdm** [comment]
@treeowl Not all of these 'containers' will be built with full utilisation of dependently types. Taken from the README:

> The [sic] are built primarily with existence in mind rather than a dependently typed construction. The latter will come later.

My immediate concern with this package is not the construction of these data structures using dependent types. For the work I do, I need the data structure itself regardless of its construction, and I will be the first to admit that my own knowledge of Idris might make coding a _fully_ dependently type variant longer to achieve than if dependent types were used. I will most likely look to providing dependently typed versions in the future, but at the moment it si not necessarily my main focus with this package.

**Comment by treeowl** [comment]
Sure, that makes sense. But the currently incorrect behavior still needs to
be fixed!

**Comment by jfdm** [comment]
You are right, it does need fixing, and if  have time in the next few days I shall look into it more.

Also I noticed that you said you don't know Idris, if you wish to learn more about Idris then please feel free to check out our documentation at:

```
http://docs.idris-lang.org
```

We also are on `#idris` on freenode.

**Comment by treeowl** [comment]
I'll take a look when I get a chance. I may also volunteer to attempt a
finger tree implementation. I've done some work on Haskell's Data.Sequence.
It would be interesting to attempt to use dependent types to prove that my
`zipWith` implementation is total—for that, of course, I'll need to learn
something about dependent types! The challenge with `zipWith` is that
finger trees are a "redundant" representation, so there is no clear way in
the Haskell type system to express that two of them have the same size.

**Comment by jfdm** [comment]
Interesting, might I also suggest looking at the `contrib` package bundled as part of Idris (new in v0.9.17) in which there are several other data structures and might give inspiration as to how to implement FingerTrees. If you do get stuff working it might be worth making a PR to the main idris repo.

**Comment by jfdm** [comment]
This issue is no longer an issue as an alternate (Dependently typed) AVL tree implementation is now used, and does not provide update functions.
