### ISSUE TITLE
Traversable instance for Dict

### ISSUE THREAD

**Issue by mgttlinger** [jfdm/idris-containers#23]
Would you be up for a `Traversable` Instance for `Dict` over the values in the dictionary?
I defined it locally as:
```idris
Ord a => Functor (Dict a) where 
  map func x = fromList $ (\(a, b) => (a, func b)) <$> toList x
Ord a => Foldable (Dict a) where   
  foldr func = foldr $ const func
Ord a => Traversable (Dict a) where 
  traverse f x = fromList <$> (traverse (\(a, b) => (MkPair a) <$> f b) $ Data.AVL.Dict.toList x)
```

**Comment by jfdm** [comment]
I don't see any reason not to have this. PR away, however, I do have a dev branch that may or may not be ahead of master. Can you make the PR to there, please.
