### ISSUE TITLE
AVL Tree and Dict functions are not total in Idris 1.0

### ISSUE THREAD

**Issue by emptyflash** [jfdm/idris-containers#27]
Idris is telling me several functions are not total with Idris 1.0. Specifically `Data.AVL.Tree.rotLeft` and `Data.AVL.Tree.rotRight`. I tried poking around to see if I could fix it, but I'm not well verse enough in Idris and it's been too long since I've thought about AVL trees.

**Comment by jfdm** [comment]
Thanks for reporting the issue.

However, when building with Idris HEAD they are reported as being total. IIRC there *was* an issue with the totality checker for 1.0 that was fixed.

Given that the latest version of idris is reporting totality, I am okay with that,

**Comment by emptyflash** [comment]
Cool, built from master and it worked, thanks! 👍
