### ISSUE TITLE
(lookup k (insert k v dict) dict) = Just v?

### ISSUE THREAD

**Issue by dckc** [jfdm/idris-containers#35]
Unlike `::` for `List`, `insert` on `Dict` seems to lose information so that I can't prove much about the results.

I wrote an analog of `lookup` that uses `HasKey` proofs (see below) and now I want to prove...

```idris
insertValue: DecEq k => Ord k => (key: k) -> (dict: Dict k v)
  -> keyValue key (insert key val dict) found = val
```

but I don't see how.

```idris
keyValue: (key: k) -> (dict: (Dict k v)) -> (pf: HasKey key dict)
  -> v
keyValue key (MkDict $ Element t inv) (IsKey (IsKey found)) =
  keyValue' key t found
    where
      keyValue': (key: k) -> (t: Tree k v) -> (found: IsKeyIn key t) -> v
      keyValue' key (Node key val _ _) Here = val
      keyValue' key (Node not_key val left r) (InRight later) =
        keyValue' key r later
      keyValue' key (Node not_key val l right) (InLeft later) =
        keyValue' key l later
```

**Comment by dckc** [comment]
Of course, this is in the coq standard library:

```coq
Lemma add_1 : forall m x y e, X.eq x y -> MapsTo y e (add x e m).
```


https://coq.inria.fr/library/Coq.FSets.FMapInterface.html
https://coq.inria.fr/library/Coq.FSets.FMapAVL.html

**Comment by jfdm** [comment]
Dict and friends are wrappers around a inner proof structure.

You'll need to look at the inner proof structure (i.e. Data.AVL.Tree) and wrap your reasoning in something for Dict.

**Comment by dckc** [comment]
thanks for the clue. For now, I'm using `List (k, v)` for my mappings / dictionaries.
