### ISSUE TITLE
AVL Tree issues

### ISSUE THREAD

**Issue by jfdm** [jfdm/idris-containers#6]
There are two types of AVL tree implementation in this project. The first, is a 'standard' implementation of AVL trees that was taken and adapted from Haskell. The second, uses dependent types to ensure that only balanced trees can be constructed.

There are issues with these implementations:
1. The standard AVL tree implementation has rotation issues. The entire balancing portion needs updating.
2. The Dependently Typed AVL came with a flaw in the left rotation functions. These need numpty checking. The affected lines are marked.
3. The Dependently Typed AVL is too strict in keeping the balance invariant true; the shape of the data structure remains fixed unless something is inserted. This will result in inefficient operations for manipulating structures---there are no in-place modifications. If the balancing invariant could be weakened to allow 'out of balance' trees, then removal and splitting and thus efficient manipulation functions could be constructed---`merge`,`split`,`remove`,`update`.

**Update** 
This issue was partially addressed by provision of a dependently typed AVL tree implementation with the invariants separated. However, there is a yet to be diagnosed problem with rotation, it is lossy.

**Comment by jfdm** [comment]
@ahmadsalim AVL Trees are lossy somewhere.

**Comment by jfdm** [comment]
Actually, i might be wrong in thinking the implementation is wrong.
Yesterday, I added mroe random test data and it appeared that nodes were being dropped, however, the test data had duplicate entries. I have added better more uniquely random test data and things are passing. However, when running tests I get this warn reach error. This might be the cause of the segfault I am getting in another program that uses the tree code. This doesn't show up during installation.

```
Data.AVL.Tree.AVLNode: inaccessible arguments reachable:
  n from PE_insert_5cf1649a arg# 4, Data.AVL.Tree.insert arg# 6, Data.AVL.Tree.rotLeft arg# 6, Data.AVL.Tree.rotRight arg# 5, with block in Data.AVL.Tree.update arg# 10
  l from Data.AVL.Tree.rotLeft arg# 6
  m from PE_insert_5cf1649a arg# 4, Data.AVL.Tree.insert arg# 6, Data.AVL.Tree.rotLeft arg# 6, Data.AVL.Tree.rotRight arg# 5, with block in Data.AVL.Tree.update arg# 10
  r from Data.AVL.Tree.rotRight arg# 5
Data.AVL.Tree.Balanced: inaccessible arguments reachable:
  n from Data.AVL.Tree.rotLeft arg# 6, Data.AVL.Tree.rotRight arg# 5
Prelude.Pairs.Element: inaccessible arguments reachable:
  pf from PE_insert_5cf1649a arg# 4, Data.AVL.Tree.insert arg# 6, Data.AVL.Tree.rotLeft arg# 5, Data.AVL.Tree.rotLeft arg# 6, Data.AVL.Tree.rotRight arg# 5, Data.AVL.Tree.rotRight arg# 6, Data.AVL.Tree.update arg# 6, with block in with block in Data.AVL.Tree.insert arg# 9, with block in with block in Data.AVL.Tree.insert arg# 11, with block in with block in Data.AVL.Tree.update arg# 9, with block in with block in Data.AVL.Tree.update arg# 11
Data.AVL.Tree.LHeavy: inaccessible arguments reachable:
  n from Data.AVL.Tree.rotLeft arg# 6
Data.AVL.Tree.RHeavy: inaccessible arguments reachable:
  n from Data.AVL.Tree.rotRight arg# 5
Data.AVL.Tree.rotLeft: inaccessible arguments reachable:
  n (no more information available)
Data.AVL.Tree.rotRight: inaccessible arguments reachable:
  n (no more information available)
Data.AVL.Tree.height, height': inaccessible arguments reachable:
  m (no more information available)
```

**Comment by david-christiansen** [comment]
Reachability errors shouldn't make your code segfault - they should just make it eat memory and be slow. They're a sign that you've used something at runtime that was declared to be compile-time only, and therefore it had to persist into the compiled code. Here, it looks like your tests are pattern-matching on the depth of the tree at some point.

**Comment by ahmadsalim** [comment]
@jfdm @david-christiansen It might also be because I might need the height of the tree to be actually be stored in the actual tree (and not the invariant). I will take a look on how this can be improved soon.

**Comment by ahmadsalim** [comment]
It might also be nice to separate the proofs from the core operations, so I may also add that to the TODO list.

**Comment by jfdm** [comment]
Just an update, I found out why my code was segfaulting. It definitely wasn't due to the containers code. It was related to the use of type-classes and over-patched code. See issue https://github.com/idris-lang/Idris-dev/issues/2406. Panic over!

Also @ahmadsalim don't chase this up to much
