### ISSUE TITLE
Improve queues

### ISSUE THREAD

**Issue by treeowl** [jfdm/idris-containers#9]
The current queue implementation does not work properly in a persistent setting. It also doesn't have much in the way of proof behind it. I've opened pull request #10 to add Okasaki-style Banker's queues. They're rather more complicated, so it's quite possible that we should keep the simpler ones as well for the times when they're appropriate.

**Comment by treeowl** [comment]
Actually, now that I think about it a bit more, the length calculation in `uncons` may have asymptotic effects. I'll try to get rid of that tomorrow or so.

**Comment by jfdm** [comment]
As I said many years ago, this stuff is nice but would be better in idris' contrib package.
